"""bench/leaderboard.py - Combine model runs into a ranked leaderboard.

Reads every runs/*.json produced by bench.run_bench and emits:
    bench/LEADERBOARD.md     - a markdown table, ranked by resolve rate
    bench/leaderboard.json   - the same data, machine-readable

Usage:
    python -m bench.leaderboard
"""

from __future__ import annotations

import json
from pathlib import Path

RUNS_DIR = Path(__file__).parent / "runs"
MD_OUT = Path(__file__).parent / "LEADERBOARD.md"
JSON_OUT = Path(__file__).parent / "leaderboard.json"


def build() -> list[dict]:
    rows = []
    for f in sorted(RUNS_DIR.glob("*.json")):
        data = json.loads(f.read_text())
        s = data["summary"]
        rows.append({
            "model": data["model"],
            "resolve_rate": s["resolve_rate"],
            "n_resolved": s["n_resolved"],
            "n_tasks": s["n_tasks"],
            "tool_precision": s["avg_tool_precision"],
            "avg_latency_s": s["avg_latency_s"],
            "avg_tokens": s["avg_tokens"],
            "by_category": s.get("by_category", {}),
        })
    rows.sort(key=lambda r: r["resolve_rate"], reverse=True)
    return rows


def to_markdown(rows: list[dict]) -> str:
    cats = sorted({c for r in rows for c in r["by_category"]})
    head = ["Model", "Resolve rate", "Solved"] + [f"{c}" for c in cats] + \
           ["Tool prec.", "Latency (s)", "Tokens"]
    lines = ["# SDLC Agent Benchmark - Leaderboard", "",
             "Execution-based resolve rate across local models on the same task "
             "suite. A task is *resolved* only when its fail->pass and pass->pass "
             "tests all pass after the agent acts.", "",
             "| " + " | ".join(head) + " |",
             "| " + " | ".join(["---"] * len(head)) + " |"]
    for r in rows:
        cat_cells = [f"{r['by_category'].get(c, {}).get('resolve_rate', '-')}" for c in cats]
        cells = [
            f"`{r['model']}`",
            f"**{r['resolve_rate']:.0%}**" if isinstance(r["resolve_rate"], float) else str(r["resolve_rate"]),
            f"{r['n_resolved']}/{r['n_tasks']}",
            *cat_cells,
            f"{r['tool_precision']}",
            f"{r['avg_latency_s']}",
            f"{r['avg_tokens']}",
        ]
        lines.append("| " + " | ".join(cells) + " |")
    lines += ["", "_Generated by `python -m bench.leaderboard`._"]
    return "\n".join(lines)


def main():
    rows = build()
    if not rows:
        print("No runs found in runs/. Run `python -m bench.run_bench --oracle` first.")
        return
    JSON_OUT.write_text(json.dumps(rows, indent=2))
    MD_OUT.write_text(to_markdown(rows))
    print(to_markdown(rows))
    print(f"\nWrote {MD_OUT} and {JSON_OUT}")


if __name__ == "__main__":
    main()
